import Head from 'next/head'
import Chillinq from '../components/Chillinq/Chillinq'


export default function Home() {
  return (
    <div className='' >
      <Head>
        <title>Chillinq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Chillinq />
    </div>
  )
}
