import Head from 'next/head'
import Chillinq from '../components/Chillinq/Chillinq'


export default function Home() {
  return (
    <div className='' >
      <Head>
        <title>Chillinq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="party" content="party fun app" />
        <meta name="chill" content="chilling app" />
        <meta name="flurt" content="flurt app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/chillinqfav.png" />
      </Head>
      <Chillinq />
    </div>
  )
}
